apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: conversao-temp
  name: conversao-temp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temp
  strategy: {}
  template:
    metadata:
      labels:
        app: conversao-temp
    spec:
      containers:
      - image: xrbsx/conversao-temperatura:latest
        name: conversao-templeratura
        resources: {}
